---
- name: Create config directory
  become: true
  file:
    path: "/etc/mastobot"
    state: directory

- name: Create mastobot config
  become: true
  copy:
    dest: /etc/mastobot/config.yaml
    mode: 0644
    content: |
      server_name: {{ server_name }}
      deploy_path: {{ mastodon_deploy_dir }}

- name: Create mastobot Bootsrap config
  become: true
  copy:
    dest: /etc/mastobot/bootstrap.yaml
    mode: 0644
    content: |
      admin_user: {{ admin_user }}
      admin_password: {{ admin_password }}
      mastodon_users: {{ mastodon_users }}

- name: Create masto_bot directory
  become: true
  file:
    path: "{{ mastodon_deploy_dir }}/masto_bot"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy mastobot
  become: true
  copy:
    dest: "{{ mastodon_deploy_dir }}/masto_bot.py"
    src: masto_bot.py
    mode: 0755

- name: Deploy mastobot bootstrap
  tags: ["mastobot"]
  become: true
  copy:
    dest: "{{ mastodon_deploy_dir }}/masto_bot_bootstrap.py"
    src: masto_bot_bootstrap.py
    mode: 0755

- name: Create mastobot startscript
  become: true
  copy:
    dest: "/usr/bin/mastobot"
    mode: 0755
    content: |
      #!/bin/bash

      export REQUESTS_CA_BUNDLE={{ ssl_ca }}
      {{ mastodon_deploy_dir }}/masto_bot.py "$@"

- name: Mastobot Bootstrap
  shell:
    cmd: "{{ mastodon_deploy_dir }}/masto_bot_bootstrap.py"
    chdir: "{{ mastodon_deploy_dir }}"
  environment:
    REQUESTS_CA_BUNDLE: "{{ ssl_ca }}"

