---
- name: Install apt packages
  tags: [install]
  become: true
  apt:
    name: "{{ apt_packages }}"
    state: present

- name: Add NGINX configuration file
  become: true
  template:
    dest: /etc/nginx/sites-enabled/default
    src:  nginx_default.conf.j2
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart nginx"

- name: Install pip packages 
  become: true
  pip:
    name: ["Mastodon.py", "click"]

- name: Create directory structure
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop: ["{{ mastodon_deploy_dir }}", "{{ mastodon_deploy_dir }}/config", "{{ mastodon_deploy_dir }}/media"]

- name: Deploy media
  become: true
  copy:
    src: bootstrap_media/
    dest: "{{ mastodon_deploy_dir }}/media/"

- name: Write pleroma config
  become: true
  template:
    dest: "{{ mastodon_deploy_dir }}/config/config.exs"
    src: config.exs.j2

