version: '3'

volumes:
  uploads:
  static:
  postgres:

networks:
  mastodon:

services:
  mastodon:
    image: jordemort/pleroma
    container_name: mastodon
    restart: unless-stopped
    env_file: .env.production
    ports:
      - 127.0.0.1:4000:4000
    depends_on:
      - postgres
    volumes:
      - ./config:/etc/pleroma
      - uploads:/var/lib/pleroma/uploads
      - static:/var/lib/pleroma/static
    networks:
      - mastodon

  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    env_file: .env.production
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mastodon
